# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255, verbose_name='Endereço')),
                ('number', models.CharField(blank=True, max_length=5, null=True, verbose_name='Número')),
                ('postalCode', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, verbose_name='DDD')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('L', 'Terreno'), ('H', 'Casa'), ('A', 'Apartamento'), ('F', 'Flat'), ('P', 'Terreno'), ('K', 'Kitnet')], max_length=1, verbose_name='Tipo')),
                ('area', models.IntegerField(verbose_name='Área')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='IPTU')),
                ('condoPrice', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Condomínio')),
                ('numberOfBathrooms', models.IntegerField(verbose_name='Banheiros')),
                ('numberOfRooms', models.IntegerField(verbose_name='Quartos')),
                ('numberOfSuites', models.IntegerField(verbose_name='Suítes')),
                ('numberOfCarParks', models.IntegerField(verbose_name='Vagas')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Address', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('surname', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='realestate',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Seller', verbose_name='Anunciante'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.State', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City', verbose_name='Cidade'),
        ),
    ]
