# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Anunciante', 'verbose_name_plural': 'Anunciantes'},
        ),
        migrations.AddField(
            model_name='realestate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Vendido'),
        ),
    ]
