# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170715_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(default=django.utils.timezone.now, max_length=2, unique=True, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
