# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170715_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
    ]
