# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_city_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(default='Bairro', max_length=30, verbose_name='Bairro'),
            preserve_default=False,
        ),
    ]
