# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_address_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='transactionType',
            field=models.CharField(choices=[('S', 'Venda'), ('R', 'Aluguel')], default='S', max_length=1, verbose_name='Tipo de Operação'),
            preserve_default=False,
        ),
    ]
