# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_realestate_transactiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='price',
        ),
        migrations.AddField(
            model_name='realestate',
            name='rentPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Alguel'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='sellPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Preço de Venda'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='sold_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vendido em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realestate',
            name='numberOfCarParks',
            field=models.IntegerField(verbose_name='Vagas de Garagem'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='IPTU'),
        ),
    ]
