# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20170715_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='IPTU'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='transactionType',
            field=models.CharField(choices=[('S', 'Venda'), ('R', 'Aluguel'), ('A', 'Venda ou Aluguel')], max_length=1, verbose_name='Tipo de Operação'),
        ),
    ]
