# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170715_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Address', verbose_name='Localização'),
        ),
    ]
