# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20170715_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='condoPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Condomínio'),
        ),
    ]
