# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20170715_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slugName',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realestate',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
