# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20170716_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slugName',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
