# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20170716_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='slugName',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='condoPrice',
            new_name='condo_price',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='numberOfBathrooms',
            new_name='number_of_bathrooms',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='numberOfCarParks',
            new_name='number_of_car_parks',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='numberOfRooms',
            new_name='number_of_rooms',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='numberOfSuites',
            new_name='number_of_suites',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='rentPrice',
            new_name='rent_price',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='sellPrice',
            new_name='sell_price',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='transactionType',
            new_name='transaction_type',
        ),
    ]
