# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20170716_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='catalog.Address'),
        ),
    ]
