# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 01:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20170717_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='Anunciante'),
        ),
    ]
