# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20170717_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='seller',
        ),
    ]
